### ISSUE TITLE
fixture.load() と schema.load()の説明が間違ってる？

### ISSUE THREAD

**Issue by mura-** [t-kojima/kinmock#6]
まちがってたらすいません。

ReadmeにかいてあるFixtureの使い方なんですが、以下が正しいのではないでしょうか

- ☓ `const fixture = require('kintone/fixture');`
- ○ `const fixture = require('kintuba/fixture');`

**Comment by t-kojima** [comment]
Issueありがとうございます！

仰る通り誤っていましたので、修正しました。

**Comment by mura-** [comment]
@t-kojima 

PRつくればよかったんですが、すいません。
最近使い始めたのでなにかあったらPRつくってみます！
